# Learning Numpy & Pandas for Data Analysis
    Structure => Numpy multidimesnsional array
    Super Fast processing
    Deals only Numerical values
    

# Creating a Numpy Array

# 1- Dimensional array

In [2]:
# Importing Numpy (Numerical Python) Module 
import numpy as np

In [3]:
# using Python List
lst = [1,2,3,4,5,6,7,8,9,10]
print(type(lst))
arr1d = np.array(lst)

<class 'list'>


In [4]:
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
type(arr1d)

numpy.ndarray

In [6]:
arr1d[0]

1

In [7]:
arr1d[0:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr1d.max()

10

In [9]:
arr1d.min()

1

In [10]:
arr1d.sum()

55

In [11]:
arr1d.all()

True

In [12]:
lst = [1,2,3,4,5,6,7,8,9,10]
double= []
for a in lst:
    double.append(a*3)
double

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30]

# Vectorized Operation

In [13]:
arr1d*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [14]:
arr1d/2

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])

In [15]:
arr1d.size

10

In [16]:
arr1d.ndim

1

In [17]:
arr1d.shape

(10,)

In [18]:
# Array Creation using Numpy arange 
arr1d = np.arange(12)
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

# 2D Array

In [19]:
# array using List
lst2d=[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]
lst2d

[[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]]

In [20]:
arr2d = np.array(lst2d)

In [21]:
arr2d                        # row and col start from 0 index

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [22]:
arr2d.shape   # (R,C)

(4, 3)

In [23]:
arr2d.ndim

2

In [24]:
arr2d+arr2d

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18],
       [20, 22, 24]])

In [25]:
arr2d*arr2d

array([[  1,   4,   9],
       [ 16,  25,  36],
       [ 49,  64,  81],
       [100, 121, 144]])

In [26]:
arr3d = np.arange(36).reshape(6,6)
arr3d

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [27]:
arr3d.ndim

2

In [28]:
arr3d.shape

(6, 6)

In [29]:
arr4d=arr3d.reshape(9,4)
arr4d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [30]:
arr4d.ndim

2

In [31]:
arr4d.shape

(9, 4)

In [32]:
arr5d=arr3d.reshape(10,4)      # error in reshaping b/c, arr3d has 36 elements and (10,4) req 40 elements
arr5d

ValueError: cannot reshape array of size 36 into shape (10,4)

In [34]:
arr1d[5]

5

In [35]:
arr1d[4:5]

array([4])

In [36]:
#index value 23 from array
arr4d[5][3]                  # row 5, 

23

In [37]:
arr4d[5,3]

23

In [38]:
arr5d=arr3d.reshape(4,9)
arr5d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [39]:
# two portion while we slcicing of an array of 2d arr arr[row,col] => [startrow:endrow,startcoloumn:endcoloumn]
arr5d[1:2,2:7]

array([[11, 12, 13, 14, 15]])

In [40]:
arr5d[1:3,5:7]

array([[14, 15],
       [23, 24]])

In [41]:
arr5d[0:,6:]

array([[ 6,  7,  8],
       [15, 16, 17],
       [24, 25, 26],
       [33, 34, 35]])

In [42]:
# if we give all arguments of array in this array perform slicing [2:3,4:5] if any argument is missing then it return an index [:,2]
# return Index
arr5d[:,-1]

array([ 8, 17, 26, 35])

In [43]:
# Return slice
arr5d[0:,8:]

array([[ 8],
       [17],
       [26],
       [35]])

In [44]:
arr5d[:,[5,8,0,3]]

array([[ 5,  8,  0,  3],
       [14, 17,  9, 12],
       [23, 26, 18, 21],
       [32, 35, 27, 30]])

In [45]:
arr5d[[0,2],[2,7]]

array([ 2, 25])

In [46]:
arr5d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [47]:
arr5d[:,::2]

array([[ 0,  2,  4,  6,  8],
       [ 9, 11, 13, 15, 17],
       [18, 20, 22, 24, 26],
       [27, 29, 31, 33, 35]])

In [48]:
arr5d[:,::-2]

array([[ 8,  6,  4,  2,  0],
       [17, 15, 13, 11,  9],
       [26, 24, 22, 20, 18],
       [35, 33, 31, 29, 27]])

In [49]:
arr5d[::2,::2]

array([[ 0,  2,  4,  6,  8],
       [18, 20, 22, 24, 26]])

In [50]:
arr3d = np.arange(64).reshape(4,4,4) #(depth , row , coloumn)

In [51]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [52]:
arr3d[2,1,2]

38

In [53]:
a= np.arange(6).reshape(3,2)
b= np.arange(6).reshape(2,3)

In [54]:
a

array([[0, 1],
       [2, 3],
       [4, 5]])

In [55]:
b

array([[0, 1, 2],
       [3, 4, 5]])

In [56]:
a*b

ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

In [57]:
b*a

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [58]:
b@a

array([[10, 13],
       [28, 40]])

In [59]:
a@b

array([[ 3,  4,  5],
       [ 9, 14, 19],
       [15, 24, 33]])

In [61]:
a= np.arange(15).reshape(5,3)
b= np.arange(10).reshape(2,5)

In [62]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [64]:
b

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [65]:
a@b

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [66]:
b@a

array([[ 90, 100, 110],
       [240, 275, 310]])

In [67]:
b.dot(a)

array([[ 90, 100, 110],
       [240, 275, 310]])

In [68]:
np.linspace(1,100,100)

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,
        12.,  13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,
        23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,
        34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,
        45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,  55.,
        56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
        67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,
        78.,  79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,
        89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99.,
       100.])

In [ ]:
np.linspace(1,100,10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

In [ ]:
a.shape, a.dtype, a.size, a.ndim

((5, 3), dtype('int32'), 15, 2)

In [ ]:
np.zeros_like(a)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

# Boolean selection Filters/ Query

In [ ]:
arr1d> 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
(arr1d> 5).sum()

5

In [ ]:
arr1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
a = [True, False, True, False, True, True, False, True, False, True]  # boolean indexing

In [ ]:
arr1d[3]

4

In [ ]:
arr1d[a]

array([ 1,  3,  5,  6,  8, 10])

In [ ]:
arr1d[arr1d>5]

array([ 6,  7,  8,  9, 10])

In [ ]:
arr1d[arr1d==5]

array([5])

In [ ]:
arr1d[arr1d%2==0]

array([ 2,  4,  6,  8, 10])

In [ ]:
arr1d[arr1d%2!=0]

array([1, 3, 5, 7, 9])

In [ ]:
arr2d = np.arange(36).reshape(4,9)

In [ ]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [ ]:
arr2d[ arr2d>10 ]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
       28, 29, 30, 31, 32, 33, 34, 35])

In [34]:
arr2d[ (arr2d>10) & (arr2d<30) ]

array([11, 12])

In [35]:
arr3d = np.arange(64).reshape(4,4,4) #(depth , row , coloumn)

In [36]:
arr3d

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [37]:
a= arr3d.ravel()          # change in c has impact on arr3d
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [43]:
b= arr3d.flatten()     # change in b has no impact on arr3d
b

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63])

In [39]:
c= arr3d.reshape(64)   # change in c has impact on arr3d
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63])

In [40]:
a[5:40]=100          # changes in a also impact on arr3d, b/c derived from arr3d by ravel()

In [41]:
a

array([  0,   1,   2,   3,   4, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100,
       100,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63])

In [42]:
arr3d

array([[[  0,   1,   2,   3],
        [  4, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100],
        [ 40,  41,  42,  43],
        [ 44,  45,  46,  47]],

       [[ 48,  49,  50,  51],
        [ 52,  53,  54,  55],
        [ 56,  57,  58,  59],
        [ 60,  61,  62,  63]]])

In [44]:
b[5:40]=200              # changes in b not make impact on arr3d, b/c derived from arr3d by flatten()
b 

array([  0,   1,   2,   3,   4, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200, 200,
       200,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63])

In [46]:
c[5:40]=300              # changes in c also impact on arr3d, b/c derived from arr3d by reshape()
c 

array([  0,   1,   2,   3,   4, 300, 300, 300, 300, 300, 300, 300, 300,
       300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300,
       300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300, 300,
       300,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63])

In [47]:
arr3d

array([[[  0,   1,   2,   3],
        [  4, 300, 300, 300],
        [300, 300, 300, 300],
        [300, 300, 300, 300]],

       [[300, 300, 300, 300],
        [300, 300, 300, 300],
        [300, 300, 300, 300],
        [300, 300, 300, 300]],

       [[300, 300, 300, 300],
        [300, 300, 300, 300],
        [ 40,  41,  42,  43],
        [ 44,  45,  46,  47]],

       [[ 48,  49,  50,  51],
        [ 52,  53,  54,  55],
        [ 56,  57,  58,  59],
        [ 60,  61,  62,  63]]])

In [45]:
arr3d

array([[[  0,   1,   2,   3],
        [  4, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100],
        [100, 100, 100, 100]],

       [[100, 100, 100, 100],
        [100, 100, 100, 100],
        [ 40,  41,  42,  43],
        [ 44,  45,  46,  47]],

       [[ 48,  49,  50,  51],
        [ 52,  53,  54,  55],
        [ 56,  57,  58,  59],
        [ 60,  61,  62,  63]]])

Concatenation of Arrays

In [ ]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [ ]:
arr2d1= arr2d[:]*5
arr2d1

array([[  0,   5,  10,  15,  20,  25,  30,  35,  40],
       [ 45,  50,  55,  60,  65,  70,  75,  80,  85],
       [ 90,  95, 100, 105, 110, 115, 120, 125, 130],
       [135, 140, 145, 150, 155, 160, 165, 170, 175]])

In [ ]:
new2d= np.concatenate((arr2d,arr2d1), axis=0)    # by default, concatenate down vertically 
new2d

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26],
       [ 27,  28,  29,  30,  31,  32,  33,  34,  35],
       [  0,   5,  10,  15,  20,  25,  30,  35,  40],
       [ 45,  50,  55,  60,  65,  70,  75,  80,  85],
       [ 90,  95, 100, 105, 110, 115, 120, 125, 130],
       [135, 140, 145, 150, 155, 160, 165, 170, 175]])

In [ ]:
new2d= np.concatenate((arr2d,arr2d1), axis=1)    #concatenate right  horizontally
new2d

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   0,   5,  10,  15,
         20,  25,  30,  35,  40],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17,  45,  50,  55,  60,
         65,  70,  75,  80,  85],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26,  90,  95, 100, 105,
        110, 115, 120, 125, 130],
       [ 27,  28,  29,  30,  31,  32,  33,  34,  35, 135, 140, 145, 150,
        155, 160, 165, 170, 175]])

In [ ]:
new2d= np.concatenate((arr2d,arr2d1), axis=None)  #concatenate both
new2d

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,   0,   5,  10,
        15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,  70,  75,
        80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130, 135, 140,
       145, 150, 155, 160, 165, 170, 175])

In [ ]:
new2d = np.vstack((arr2d,arr2d1))   #concatenate vertically
new2d

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26],
       [ 27,  28,  29,  30,  31,  32,  33,  34,  35],
       [  0,   5,  10,  15,  20,  25,  30,  35,  40],
       [ 45,  50,  55,  60,  65,  70,  75,  80,  85],
       [ 90,  95, 100, 105, 110, 115, 120, 125, 130],
       [135, 140, 145, 150, 155, 160, 165, 170, 175]])

In [ ]:
new2d = np.hstack((arr2d,arr2d1))   # concatenate horizontally
new2d

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   0,   5,  10,  15,
         20,  25,  30,  35,  40],
       [  9,  10,  11,  12,  13,  14,  15,  16,  17,  45,  50,  55,  60,
         65,  70,  75,  80,  85],
       [ 18,  19,  20,  21,  22,  23,  24,  25,  26,  90,  95, 100, 105,
        110, 115, 120, 125, 130],
       [ 27,  28,  29,  30,  31,  32,  33,  34,  35, 135, 140, 145, 150,
        155, 160, 165, 170, 175]])

In [ ]:
a = np.arange(9).reshape(3,3)
b = np.arange(10,19).reshape(3,3)

In [ ]:
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
b

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [ ]:
dstack= np.dstack((a,b))  # concatenate depth wise
dstack

array([[[ 0, 10],
        [ 1, 11],
        [ 2, 12]],

       [[ 3, 13],
        [ 4, 14],
        [ 5, 15]],

       [[ 6, 16],
        [ 7, 17],
        [ 8, 18]]])

In [ ]:
arr2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26],
       [27, 28, 29, 30, 31, 32, 33, 34, 35]])

In [ ]:
np.split(arr2d, 3, axis=1)  # split into 3 arrays horizontally

[array([[ 0,  1,  2],
        [ 9, 10, 11],
        [18, 19, 20],
        [27, 28, 29]]),
 array([[ 3,  4,  5],
        [12, 13, 14],
        [21, 22, 23],
        [30, 31, 32]]),
 array([[ 6,  7,  8],
        [15, 16, 17],
        [24, 25, 26],
        [33, 34, 35]])]

In [ ]:
np.split(arr2d, 2)       # axis by default 0, vertically

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
        [27, 28, 29, 30, 31, 32, 33, 34, 35]])]

In [ ]:
np.split(arr2d, 2, axis=0)

[array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17]]),
 array([[18, 19, 20, 21, 22, 23, 24, 25, 26],
        [27, 28, 29, 30, 31, 32, 33, 34, 35]])]

In [ ]:
a = np.arange(12).reshape(4,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [ ]:
b = np.arange(3).reshape(1,3)*10
b

array([[ 0, 10, 20]])

In [ ]:
s2= pd.Series([10, 20, 30, 40, 50, 60, 70, 80], index=[0,1,2,3,4,5,6,7]) 
s2

0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
dtype: int64